# Generated by Django 5.2.7 on 2026-02-09 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Honorários da Causa Trabalhista', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('PAG', 'Pago'), ('CAN', 'Cancelado')], default='PEN', max_length=3)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorarios', to='core.cliente')),
            ],
        ),
    ]
